---
title: "Visualization_and_EDA_2"
author: "Arielle"
date: "10/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("thomasp85/patchwork")
library (tidyverse)
library (ggridges)
library (patchwork)
```


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## Making new plots

```{r}
weather_df %>% 
  ggplot (aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maxiumum Daily Temperature",
    caption = " Data from the rnoaa package"
  )

weather_df %>% 
  ggplot (aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maxiumum Daily Temperature",
    caption = " Data from the rnoaa package") +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15c", "0", "15"
  ))

weather_df %>% 
  ggplot (aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maxiumum Daily Temperature",
    caption = " Data from the rnoaa package") +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15c", "0", "15"
  )) +
  scale_y_continuous(
    trans = "sqrt"
  )

```

#### Colors 

```{r}
weather_df %>% 
  ggplot (aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maxiumum Daily Temperature",
    caption = " Data from the rnoaa package"
  ) +
  scale_color_hue (
    name = "Weather Station",
    h = c(50, 250)
  )
```

## Viridis 

```{r}
ggp_base= 
weather_df %>% 
  ggplot (aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .5) +
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature",
    y = "Maxiumum Daily Temperature",
    caption = " Data from the rnoaa package"
  ) +
  viridis :: scale_color_viridis(
    name = "Weather Station",
    discrete = TRUE
  )
ggp_base
```

### Themes
```{r}
ggp_base +
  theme(legend.position = "bottom")

ggp_base +
  theme_minimal() +
  theme(legend.position = "bottom")
```

### More than one Dataset 

```{r}
central_park = 
  weather_df %>% 
  filter(name== "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name== "Waikiki_HA")

ggplot(data= waikiki, aes(x = date, y = tmax, color = name)) + geom_point()

ggplot(data= waikiki, aes(x = date, y = tmax, color = name)) + geom_point()+
  geom_line(data = central_park)

ggplot(data= waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp)) +
  geom_line(data = central_park)
```

### PatchWork

```{r}
ggp_scatter= 
  weather_df %>% 
  ggplot(aes(x= tmin, y = tmax)) +
  geom_point() 

ggp_density= 
  weather_df %>% 
  ggplot(aes(x= tmin)) +
  geom_density() 

ggp_box= 
  weather_df %>% 
  ggplot(aes(x= name, y = tmax)) +
  geom_boxplot()

ggp_scatter + ggp_density

ggp_scatter + (ggp_density + ggp_box)
```

### Data Maninpulation

```{r}
  weather_df %>% 
  mutate(
    name = factor(name),
    name = fct_relevel(name, "Waikiki_HA", "CentralPark_NY")
  ) %>% 
  ggplot(aes(x= name, y = tmax, color = name)) +
  geom_boxplot()

  weather_df %>% 
  mutate(
    name = factor(name),
    name = fct_reorder(name, tmax)
  ) %>% 
  ggplot(aes(x= name, y = tmax, color = name)) +
  geom_boxplot()
```

### restucture the plot

```{r}
weather_df %>% 
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temperature"
  ) %>% 
  ggplot (aes(x = temperature, fill = observation))+
  geom_density (alpha = .5) +
  facet_grid(~name) +
  theme(legend.position = "bottom")
```
```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  mutate(wt_gain = gd18_weight - gd0_weight,
         day_of_tx = as.numeric(day_of_tx))

fas_data = left_join(pup_data, litter_data, by = "litter_number") 
```

```{r}
fas_data %>% 
  pivot_longer(
    pd_ears : pd_walk,
    names_to = "outcome",
    values_to = "pn_day"
  ) %>% 
    drop_na( dose, day_of_tx, pn_day) %>% 
  mutate(
    outcome = factor(outcome),
    outcome = fct_reorder (outcome, pn_day)
  ) %>% 
  ggplot (aes(x = dose, y = pn_day)) +
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
```

